### ISSUE TITLE
How to set min age

### ISSUE THREAD

**Issue by aayush19973636** [akshaynathr/Vaccine-Spotter-India#1]

**Comment by akshaynathr** [comment]
Hi Aayush,
Currently the script do not support age based filter. When I created the script the vaccines were available only to 45+.
It will sent an alert whenever a new slot is available for all the age type.
I will add the age based filter soon.

Thanks,
Akshaynath

**Comment by akshaynathr** [comment]
Hi ,
Added new feature to filter the result with age. 
In the latest version of the script you can see 'age_limit = [18,45] .
Remove the age you don't need.
Setting 'age_limit = [18]' will return only results of 18+ vaccine slots.

Thanks,
Akshaynath
