### ISSUE TITLE
Unable to get a response from the api

### ISSUE THREAD

**Issue by multitude0099** [akshaynathr/Vaccine-Spotter-India#3]
unable to get a response from cowin api 
 response status code 403

even the url https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=297&date=06-05-2021 returns {"centers":[]}

**Comment by arpitgothi** [comment]
User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36/

add this as a header

**Comment by multitude0099** [comment]
[solved]
need to add headers

```sh
api= "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=" + __pincode + "&date=" + __date
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}
response = requests.get(api, headers = headers)```

**Comment by arpitgothi** [comment]
> [solved]
> need to add headers
> 
> ```shell
> api= "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=" + __pincode + "&date=" + __date
> headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}
> response = requests.get(api, headers = headers)```
> ```

very firstly I tried this but not working

**Comment by akshaynathr** [comment]
Thanks @multitude0099  for fixing this.
